### ISSUE TITLE
cutting orthogonal to tubes ends up with two non connected polygons 

### ISSUE THREAD

**Issue by TecDroiD** [julienr/meshcut#17] opened 2020-08-22 15:32 UTC
Hi there,
I try to slice a vertical tube along the xy plane. the result is two circular polygones which are not connected. the outer one is considered as complete object and covers the inner one.

I tried to visualize my results with matplotlib:
![tube](https://user-images.githubusercontent.com/122358/90959446-8293a780-e49b-11ea-9110-9e9bdd491f43.png)

this is the test object I created using openSCAD.

[testtube.stl.txt](https://github.com/julienr/meshcut/files/5112580/testtube.stl.txt)

If polygones had normals, I could look them up to see what's inside and outside.. 
To my understanding, if a triangle is connected to the plane, it's normal must be projected onto the plane and should be normalized after..
 
I currently play around with your code to set the loaded stl.mesh's normals into your mesh object but since I'm completely new to numpy I have hard times recalculating the normals. I currently just ignore z because that's the normal to my plane

Here's the code I used to create that image.. 

[buildspace.py.txt](https://github.com/julienr/meshcut/files/5112607/buildspace.py.txt)

**Comment by julienr** [comment] 2020-08-31 19:50
Hi, thank you for the report !

I am not sure I 100% understand what you are trying to achieve, but I tried to slice your provided stl with a plane on the xy axis and this seems to work (this is using a modified `examples/1_stl_sphere_cut.py`:

<img src="https://user-images.githubusercontent.com/506602/91760497-c2613a00-ebd3-11ea-8e54-4cd7031f8ff9.png" width="500px" />

Note though that meshcut is just returning a list of polylines. It's not actually computing two new meshes. What output are you expecting ?

As a side not, I don't think the normals of the faces matter when cutting the mesh.

**Comment by julienr** [comment] 2022-01-04 21:59
Closing this as a duplicate of #11

**Closed by julienr** 2022-01-04 21:59 UTC
