### ISSUE TITLE
cross section

### ISSUE THREAD

**Issue by superzanti** [julienr/meshcut#1] opened 2016-10-04 23:55 UTC
I'm using your library for a program I'm making. It works very well except that when I run the cross_section code, the returned arrays seem to build up points of a line. When I connect all these points some appear to because I'm not sure where to connect the start and in points of each array.

Here I have a teapot.stl and here is the result I got out by "connecting the dots" if you will.

[dots](http://i.imgur.com/r6iF3TG.png)

[connected dots](http://i.imgur.com/QMJ7IXh.png)

So I have no idea where to connect the start and end points. Is there something I'm missing?

[This is the STL I'm using](http://www.thingiverse.com/thing:821)

**Comment by julienr** [comment] 2016-10-10 19:52
I think the problem is due to the fact that the teapot mesh is not manifold : it has holes and basically consists of two parts.
By closing the holes in meshlab and merging close vertices ([teapot.ply.zip](https://github.com/julienr/meshcut/files/520263/teapot.ply.zip)), I get the following cut, which looks correct to me. The reason why there are two parts is because the lid is a separate part.
 
<img width="966" alt="screen shot 2016-10-10 at 21 36 32" src="https://cloud.githubusercontent.com/assets/506602/19248641/a0272fa6-8f31-11e6-8209-1bb12bbd90fe.png">

[Here is a nice video](https://www.youtube.com/watch?v=oDx0Tgy0UHo) about fixing non-manifold meshes in meshlab.

Does this help ?

**Comment by superzanti** [comment] 2016-10-10 20:04
Unfortunately, I did try completely closed meshes.

When I do a sphere I get an array of polylines. When I draw all the polylines I don't get a closed circle but instead a "C" shape.

**Comment by julienr** [comment] 2016-10-10 20:08
> When I do a sphere I get an array of polylines. When I draw all the polylines I don't get a closed circle but instead a "C" shape.

Sounds like a bug. Can you provide an example .ply where you observe this behavior ?

**Comment by superzanti** [comment] 2016-10-10 20:26
Attached is a zip of the 1mm Diameter Sphere that I am using that I created in solidworks. It is an STL file.

Included is also a SVG generated using the array of polylines obtained from the meshcut.cross_section fuction. You'll notice that at the bottom left corner of the circle there is a gap making the polyline not a complete closed loop.

Thanks for looking into this.

[1mmDiameterSphere.zip](https://github.com/julienr/meshcut/files/520363/1mmDiameterSphere.zip)

**Comment by julienr** [comment] 2016-10-11 20:20
The problem is that STL files store vertices per face. If a vertex belongs to N faces, there will be N copies of this vertex in the file. So each face will look like a separate mesh to meshcut.

The solution is to do a preprocessing step to merge close vertices and recompute the face indices. I have implemented this in [1_stl_sphere_cut.py](https://github.com/julienr/meshcut/blob/master/examples/1_stl_sphere_cut.py) using your STL sphere as an example. Hope you don't mind me putting the .stl in the repo ?

Note that the "merge close vertices" implementation in this script is quite naive and will take a lot of time and memory if you have a big mesh. You might want to look at [libigl implementation](https://github.com/libigl/libigl/blob/master/include/igl/remove_duplicates.h) if you need to process larger meshes.

With that script, I get the following result, which looks good to me.

<img width="581" alt="screen shot 2016-10-11 at 22 14 09" src="https://cloud.githubusercontent.com/assets/506602/19286952/0cecad18-9000-11e6-86b9-119a41a3228b.png">

**Comment by superzanti** [comment] 2016-10-11 20:31
Wow thank you so much for working with me on this and taking the initiative to do so much to make sure this would work for me.

I'm looking into your implementation now. I definitely don't mind if you use my STL.

**Closed** 2018-07-09 08:29 UTC
